[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-socketio>=5.5.1",
    "flask>=3.1.0",
    "requests>=2.32.3",
    "eventlet>=0.39.1",
    "paho-mqtt>=2.1.0",
]
